/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-04 01:53:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/top.jsp", Long.valueOf(1683163238669L));
    _jspx_dependants.put("/WEB-INF/views/common/bottom.jsp", Long.valueOf(1682816752623L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>index</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--  상단 -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://getbootstrap.com/docs/5.2/assets/css/docs.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\" />\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<title>top</title>\r\n");
      out.write("<style>\r\n");
      out.write(".menu1:hover:not(.active){color: rgb(51, 51, 51);}\r\n");
      out.write("\r\n");
      out.write(".btjipsa{width: 138px; height: 58px; background: rgb(26, 188, 156); border-style: none; border-radius: 4px;}\r\n");
      out.write(".topCont{width: 1200px; max-width: none !important; margin: 0 auto;}\r\n");
      out.write(".logo{width: 160px;}\r\n");
      out.write(".menu1{font-size: 23px; font-family: 'Noto Sans KR', sans-serif; font-weight: 700; margin: 10px; color: rgb(51, 51, 51); text-decoration: none;}\r\n");
      out.write(".menu2{font-size: 23px; font-family: 'Noto Sans KR', sans-serif; font-weight: 700; margin: 10px; color: white;}\r\n");
      out.write(".topLeft{margin-left: 5%; display: inline;}\r\n");
      out.write(".topRight{margin-left: 15%; display: inline;}\r\n");
      out.write("#top_hr{border: 20px solid rgb(26, 188, 156); opacity: 1; margin: 0;}\r\n");
      out.write("#top_hr2{border: 1px solid gray;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header> \r\n");
      out.write("	<hr id=\"top_hr\">\r\n");
      out.write("	<br>\r\n");
      out.write("	<div>\r\n");
      out.write("	<div class=\"topCont\"> \r\n");
      out.write("		<div class=\"topLeft\" style=\"color: inherit;\">\r\n");
      out.write("	    	<a class=\"menu1\"><img src=\"resources/image/logo.png\" alt=\"logo\" class=\"logo\"></a>\r\n");
      out.write("		    <a class=\"menu1\">집사매칭</a>\r\n");
      out.write("		    <a class=\"menu1\">이용후기</a>\r\n");
      out.write("		    <a class=\"menu1\">고객센터</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"topRight\">    \r\n");
      out.write("		    <a class=\"menu1\" href=\"login.me\">로그인</a>\r\n");
      out.write("		    <a class=\"menu1\">회원가입</a>\r\n");
      out.write("			<button class=\"btjipsa menu2\" type=\"submit\">집사 지원</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<hr id=\"top_hr2\">\r\n");
      out.write("</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!-- 로그인 이후 상단 -->\r\n");
      out.write("\r\n");
      out.write("<!--                       상단 필요한 부분            -->\r\n");
      out.write("<!-- 로그인 전 상단 킬때만 씀 -->\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!--                      상단 굳이 필요없는 부분        -->\r\n");
      out.write("<!-- 회원가입 -->\r\n");
      out.write("<!-- 로그인 창 -->\r\n");
      out.write("\r\n");
      out.write("<!-- 아이디 비번 찾고 비번 재설정 결과 -->\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!--  하단은 항상 켜놓기 -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://getbootstrap.com/docs/5.2/assets/css/docs.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\" />\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<title>bottom</title>\r\n");
      out.write("<style>\r\n");
      out.write(".botCent{text-align: center; width: 1200px; max-width: none !important; margin: 0 auto;}\r\n");
      out.write("a:hover:not(.active){color: rgb(127, 127, 127);}\r\n");
      out.write(".bot_hr{border: 1px solid gray;}\r\n");
      out.write("#foot_hr{border: 20px solid rgb(26, 188, 156); opacity: 1; margin: 0;}\r\n");
      out.write(".left{text-align: left; display: inline-block;}\r\n");
      out.write(".right{display: inline-block; text-align: left;}\r\n");
      out.write(".right2{display: inline-block; text-align: right; font-size: 14px; font-family: 'Noto Sans KR', sans-serif; font-weight: 300; color: rgb(127, 127, 127); text-decoration: none;}\r\n");
      out.write(".bottomUl{list-style:none;}\r\n");
      out.write("#infocenter{font-size: 24px; font-family: 'Noto Sans KR', sans-serif;  font-weight: 700; margin: 10px; color: rgb(127, 127, 127); text-decoration: none;}\r\n");
      out.write(".infophone{font-size: 21px; font-family: 'Noto Sans KR', sans-serif; font-weight: 300; margin: 10px; color: rgb(127, 127, 127); text-decoration: none;}\r\n");
      out.write(".infoKakao{font-size: 21px; font-family: 'Noto Sans KR', sans-serif; font-weight: 300; margin: 70px; color: rgb(127, 127, 127); text-decoration: none;}\r\n");
      out.write(".info{font-weight: 300; font-style: bold; font-size: 16px; font-family: 'Noto Sans KR', sans-serif; margin: 10px; color: rgb(127, 127, 127); text-decoration: none;}\r\n");
      out.write("#kakao{width: 64px; display: block; border-radius: 100%; margin: 0px auto;}\r\n");
      out.write("#up{width: 64px; display: block; border-radius: 100%; margin: 0px auto;}\r\n");
      out.write("#up2{width: 64px; display: block; border-radius: 100%; margin: 0px auto;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer> \r\n");
      out.write("	<div>\r\n");
      out.write("		<div class=\"botCent\"> \r\n");
      out.write("		  	<div class=\"left\"> \r\n");
      out.write("			  	<ul class=\"bottomUl\">\r\n");
      out.write("				  	<li><a id=\"infocenter\">고객만족센터</a></li>\r\n");
      out.write("				  	<li><a class=\"infophone\">1234-5678</a></li>\r\n");
      out.write("				  	<li><a class=\"info\">09:00 ~ 17 : 00</a></li>\r\n");
      out.write("				  	<li><a class=\"info\">점심시간 12:00 ~ 13:00</a></li>\r\n");
      out.write("				  	<li><a class=\"info\">jipsanara@jsnr.co.kr</a></li>\r\n");
      out.write("				  	<li><a class=\"infophone\">제휴/마케팅</a><a class=\"info\">jsnrfd@jsnr.co.kr</a></li>\r\n");
      out.write("			  	</ul>\r\n");
      out.write("		  	</div>\r\n");
      out.write("		  	<div class=\"right\"> \r\n");
      out.write("			  	<ul class=\"bottomUl\">\r\n");
      out.write("				  	<li></li>\r\n");
      out.write("				  	<li></li>\r\n");
      out.write("				  	<li><a class=\"infophone\">집사나라 공식사이트</a></li>\r\n");
      out.write("				  	<li><a class=\"info\">(주) 집사나라 | 대표자 : 박신우</a></li>\r\n");
      out.write("				  	<li><a class=\"info\">사업자등록번호 : 123-15-5456-789</a></li>\r\n");
      out.write("				  	<li><a class=\"info\">통신판매업신고 : 제 - 2023 - 서울 -123</a></li>\r\n");
      out.write("				  	<li><a class=\"info\">본사 서울 중구 남대문로1 KH정보교육</a></li>\r\n");
      out.write("			  	</ul>\r\n");
      out.write("		  	</div>\r\n");
      out.write("		  	<div class=\"right\">\r\n");
      out.write("	  			<a class=\"infoKakao\">카카오톡 문의</a>\r\n");
      out.write("	  			<a><img src=\"resources/image/kakao.png\" id=\"kakao\"></a>\r\n");
      out.write("	  			<pre>	  			</pre>\r\n");
      out.write("		  	</div>\r\n");
      out.write("	  	</div>\r\n");
      out.write("	  	<div class=\"right\" id=\"upToTop\" style=\"position: fixed; bottom: 150px; right: 15%;\">\r\n");
      out.write("  			<img class=\"up\" src=\"resources/image/uptotop.png\" onmouseover=\"this.src='resources/image/uptotop2.png'\" onmouseout=\"this.src='resources/image/uptotop.png'\" id=\"up\">\r\n");
      out.write("	  	</div>\r\n");
      out.write("	\r\n");
      out.write("		<br><hr class=\"bot_hr\"><br>\r\n");
      out.write("		<div class=\"botCent\">\r\n");
      out.write("			<div class=\"right2\">\r\n");
      out.write("				<ul class=\"bottomUl\">\r\n");
      out.write("					<li><a>Copyright (C) 2023 JSNR. All Rights Reserved</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"right2\">	\r\n");
      out.write("				<ul class=\"bottomUl\"> \r\n");
      out.write("					<li><a>이용약관 |</a><a> 개인정보처리</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br>\r\n");
      out.write("	</div>\r\n");
      out.write("	<hr id=\"foot_hr\">\r\n");
      out.write("</footer>\r\n");
      out.write("<script>\r\n");
      out.write("	var upToTop = () => {\r\n");
      out.write("		let up = document.getElementById('up');\r\n");
      out.write("			window.addEventListener('scroll', () => {\r\n");
      out.write("				if (document.querySelector('html').scrollTop > 10) {\r\n");
      out.write("				up.style.display = \"block\";\r\n");
      out.write("		   		} else {\r\n");
      out.write("		      	up.style.display = \"none\";\r\n");
      out.write("		   		}\r\n");
      out.write("		  	})\r\n");
      out.write("			\r\n");
      out.write("			up.addEventListener('click', () => {\r\n");
      out.write("		    	window.scrollTo({ top: 0, left: 0, behavior: 'smooth' })\r\n");
      out.write("			})\r\n");
      out.write("		};\r\n");
      out.write("		upToTop();\r\n");
      out.write("		\r\n");
      out.write("</script>	\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
